const ImagePath= {
    
    Home:require('../../assets/Home.png'),
    Week_Prompt:require('../../assets/Week_Prompt.png'),
    Group:require('../../assets/Group.png'),
    Chat:require('../../assets/Chat.png'),
    Profile:require('../../assets/Profile.png'),
    hideEye:require('../../assets/hideEye.png'),
    showEye:require('../../assets/showEye.png'),
    loginImg:require('../../assets/loginImg.png'),
    More:require('../../assets/More.png'),
    profileImage:require('../../assets/profilePhoto.png'),
    cameraIcon:require('../../assets/cameraIcon.png'),
    meditationRound:require('../../assets/meditationRound.png'),
    chevronRight:require('../../assets/chevronright.png'),
    facilitatorProfile:require('../../assets/facilitatorProfile.png'),
    vector:require('../../assets/Vector.png'),
    backBtn:require('../../assets/backBtn.png'),
    chatGroup:require('../../assets/chatGroup.png'),
    splashScreen:require('../../assets/SplashScreen.png'),
    attachment:require('../../assets/Attachment.png'),
    send:require('../../assets/Send.png'),
    //
  smile: require('../../assets/smiling_face.png'),
  Line: require('../../assets/Line.png'),
  Tag: require('../../assets/Tags.png'),
  //Group: require('../../assets/group.png'),
  formkit: require('../../assets/formkit.png'),
  lady: require('../../assets/lady.png'),
  One: require('../../assets/one.png'),
  Two: require('../../assets/two.png'),
  Three: require('../../assets/three.png'),
  Four: require('../../assets/four.png'),
  About: require('../../assets/about.png'),
  Write: require('../../assets/write.png'),
  Yoga: require('../../assets/yoga.png'),
  Chevron: require('../../assets/chevronright.png'),
  Calendar: require('../../assets/calendar.png'),
  ChevronWhite: require('../../assets/chevronrightwhite.png'),
  ChevronBlue: require('../../assets/bluechevron.png'),
  FrameOne: require('../../assets/Frame1.png'),
  FrameTwo: require('../../assets/Frame2.png'),
  FrameThree: require('../../assets/Frame3.png'),
  FrameFour: require('../../assets/Frame4.png'),
  FrameFive: require('../../assets/Frame5.png'),
  FrameSix: require('../../assets/Frame6.png'),
  Share: require('../../assets/share.png'),
  Tree: require('../../assets/treeImage.png'),
};
export default ImagePath;
