export const text = {
    //WeekPrompt.js
    WELCOME_MESSAGE: "Welcome back, Sarina!",
    SUBTITLE_MESSAGE: "What do you need when you are having a hard day?",
    WHY_IT_MATTERS: "Why It Matters",
    SOME_EXAMPLE: "Some Example",
    //Login.js
    LOGIN_ERROR_TITLE: 'Error!',
    LOGIN_ERROR_MESSAGE_EMPTY: 'Please enter your Email & Password',
    LOGIN_ERROR_MESSAGE_INVALID_EMAIL: 'Please enter valid Email Address',
    LOGIN_ERROR_MESSAGE_EMPTY_PASSWORD: 'Please enter your Password',
    LOGIN_ERROR_MESSAGE_INVALID_CREDENTIALS: 'Invalid email or password',
    LOGIN_ERROR_MESSAGE_GENERIC: 'An error occurred during login. Please try again.',
    LOGIN_SUCCESS_MESSAGE: 'Login Successful',
    //Group.js
    GROUP_HEADER_TEXT: 'Your Group',
    GROUP_GUIDELINES_TEXT: 'Group Guidelines',
    GROUP_DETAILS_TITLE: 'Power Moms',
    GROUP_SCHEDULE: 'Monday @3:00 pm ET/6:00 pm ET',
    GROUP_DESCRIPTION: 'A safe and nurturing space for moms-to-be to connect, share, and explore their unique journeys through motherhood.',
    FACILITATOR_TITLE: 'Know your Facilitator',
    FACILITATOR_DETAILS_TITLE: 'Aimée is an RN, certified nurse midwife, mother, and childbirth educator. She loves the intimacy created when deeper connections are formed, and believes that birthing people have better outcomes in a strong, supportive community.',
    MEET_YOUR_GROUP_TITLE: 'Meet Your Group',
    NEED_GROUP_CHANGE_TEXT: 'Need A Group Change',
    //GroupGuidlines.js
    BACK_BUTTON: 'Back',
    GROUP_GUIDELINES_TITLE: 'Group Guidelines',
    INTRO_TEXT: 'Your group is a place to express your emotions about your experience and be open, as you listen, get to know other people, and hear about their process. Now here are a few group agreements we request our members to keep in mind for their group interactions:',
    GUIDELINE_1: 'Be open and curious, the point of this group is to ask other people questions to get to know them as people: what makes them tick, gives them pause, and keeps them going. Ask questions, empathize, be vulnerable.',
    GUIDELINE_2: 'Groups are confidential, respect people’s privacy as you’d want yours respected.',
    GUIDELINE_3: 'Please respect other people’s views on hot-button issues.',
    GUIDELINE_4: 'Do not talk negatively about members on chat or in group.',
    FEEDBACK_TEXT: 'If you have feedback or concerns, you can reach out directly to',
    EMAIL_ADDRESS: 'care@getsoulside.com',
    //Profile.js
    TITLE: 'Profile',
    LOGOUT: 'Logout',
    EMAIL_LABEL: 'Email Address',
    EMAIL_PLACEHOLDER: 'Enter your email',
    MOBILE_LABEL: 'Mobile no.',
    MOBILE_PLACEHOLDER: '9109365511',
    STATUS_LABEL: 'Current Status',
    STATUS_PLACEHOLDER: 'Pregnant',
    MEMBER_SINCE_LABEL: 'Member Since',
    MEMBER_SINCE_PLACEHOLDER: 'Enter Date',
    DUE_DATE_LABEL: 'Due Date',
    DUE_DATE_PLACEHOLDER: 'Enter Date',
    CHOOSE_IMAGE_SOURCE: 'Choose Image Source',
    TAKE_PHOTO: 'Take Photo',
    SELECT_FROM_GALLERY: 'Select from Gallery',
    CANCEL: 'Cancel',
    GET_WELLNESS_SCORE_TITLE: 'Get your mental wellness score',
    GET_WELLNESS_SCORE_DESCRIPTION: 'Get your mental wellness score for the week.',
    //HomeScreen.js
    POWER_MOMS: 'Power Moms',
    ABOUT_US: 'About Us',
    WRITE_TO_US: 'Write to Us',
    GOOD_AFTERNOON: 'Good Afternoon,',
    SARINA: 'Sarina!',
    THURSDAY: 'Thursday',
    UPCOMING_SESSION: 'Upcoming Session',
    OCT_7TH_2023_10_PM_ET: 'Oct 7th, 2023, 10:00 pm ET',
    SIX_GOING: '6 going',
    BY_AIMEE_WILLIAMS: 'By Aimée Williams',
    ADD_TO_CALENDAR: 'Add to Calendar',
    MARK_RSVP: 'Mark RSVP',
    MENTAL_WELLNESS_CHECKING: 'Mental wellness checking',
    GET_YOUR_MENTAL_WELLNESS_SCORE: 'Get your mental wellness score',
    GET_YOUR_MENTAL_WELLNESS_SCORE_FOR_THE_WEEK: 'Get your mental wellness score for the week',
    THURSDAY_UPCOMING_SESSION: 'Thursday-Upcoming Session',
    THE_SESSION_LINK: 'The session link appears here 15 minutes before the session starts. Meanwhile, fill out the Mood Questionnaire and get your Mental Wellness Score now.',
    THIS_WEEKS_PROMPT: 'This Week’s Prompt',
    WHAT_DO_YOU: 'What do you need when you are having a hard day?',
    CHECK_NOW: 'Check Now',
    MEET_YOUR_GROUP: 'Meet Your Group',
    VIEW_ALL: 'View All',
    REFER_A_FRIEND: 'Refer A Friend',
    SHARE_THE_SUPPORT: 'Share the support you\'ve found here with friends and strengthen our community together.',
    SHARE_LINK: 'Share Link',
    //ChatStack.js
    CHAT_MAIN_SCREEN_NAME:"Chat Main",
    CHAT_DETAILS_SCREEN_NAME:"Chat Details",
    //GroupStack.js
    GROUP_MAIN_SCREEN_NAME:"GroupMain",
    GROUP_GUIDELINES_SCREEN_NAME:"GroupGuidlines",
    //LoginStack.js
    LOGIN_SCREEN_NAME:"Login",
    MAIN_SCREEN_NAME:"Main",
    //NavigationTabRoutes.js
    INITIAL_ROUTE_NAME:"Home",
    HOME_SCREEN_NAME:"Home",
    WEEK_PROMPT_SCREEN_NAME:"Week Prompt",
    GROUP_SCREEN_NAME:"Group",
    CHAT_SCREEN_NAME:"Chat",
    PROFILE_SCREEN_NAME:"Profile",
}
//promptSection.js
export const values = [
    "It's good to be aware of your needs, and accept that you have needs. Sometimes you might forget you have needs when you are taking care of others. pregnant or parenting.",
    "Being aware of what works for you or helps you, gives you a little something to share with your people beforehand.",
  ];

//promptSection2.js
export const content = [
    {
      head: 'Seeking Solitude',
      description: 'Sometimes, you might need a peaceful, distraction-free space.',
    },
    {
      head: 'Immediate Conversations',
      description: 'Others find comfort in discussing things right away.',
    },
  ];  