const ImagePath= {
    
    Home:require('../../Assets/Home.png'),
    Week_Prompt:require('../../Assets/Week_Prompt.png'),
    Group:require('../../Assets/Group.png'),
    Chat:require('../../Assets/Chat.png'),
    Profile:require('../../Assets/Profile.png'),
    hideEye:require('../../Assets/hideEye.png'),
    showEye:require('../../Assets/showEye.png'),
    loginImg:require('../../Assets/loginImg.png'),
    More:require('../../Assets/More.png'),
    profileImage:require('../../Assets/profilePhoto.png'),
    cameraIcon:require('../../Assets/cameraIcon.png'),
    meditationRound:require('../../Assets/meditationRound.png'),
    chevronRight:require('../../Assets/chevronright.png'),
    facilitatorProfile:require('../../Assets/facilitatorProfile.png'),
    vector:require('../../Assets/Vector.png'),
    backBtn:require('../../Assets/backBtn.png'),
    chatGroup:require('../../Assets/chatGroup.png'),
    splashScreen:require('../../Assets/SplashScreen.png'),
    //
  smile: require('../../Assets/smiling_face.png'),
  Line: require('../../Assets/Line.png'),
  Tag: require('../../Assets/Tags.png'),
  //Group: require('../../Assets/group.png'),
  formkit: require('../../Assets/formkit.png'),
  lady: require('../../Assets/lady.png'),
  One: require('../../Assets/one.png'),
  Two: require('../../Assets/two.png'),
  Three: require('../../Assets/three.png'),
  Four: require('../../Assets/four.png'),
  About: require('../../Assets/about.png'),
  Write: require('../../Assets/write.png'),
  Yoga: require('../../Assets/yoga.png'),
  Chevron: require('../../Assets/chevronright.png'),
  Calendar: require('../../Assets/calendar.png'),
  ChevronWhite: require('../../Assets/chevronrightwhite.png'),
  ChevronBlue: require('../../Assets/bluechevron.png'),
  FrameOne: require('../../Assets/Frame1.png'),
  FrameTwo: require('../../Assets/Frame2.png'),
  FrameThree: require('../../Assets/Frame3.png'),
  FrameFour: require('../../Assets/Frame4.png'),
  FrameFive: require('../../Assets/Frame5.png'),
  FrameSix: require('../../Assets/Frame6.png'),
  Share: require('../../Assets/share.png'),
  Tree: require('../../Assets/treeImage.png'),
};
export default ImagePath;
